/*
 * DoubleListApp.java
 * @auther MHayes
 * @version 2009-01-10
 */

package page288_LinkedList;

/**
 *
 * @author Mark Hayes
 */
public class DoubleListAppGUI extends javax.swing.JFrame {

    // Instance variables
    DoubleList names = new DoubleList();

    /** Creates new form DoubleListApp */
    public DoubleListAppGUI() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        scrollPaneList = new javax.swing.JScrollPane();
        txtAreaList = new javax.swing.JTextArea();
        btnInsertHead = new javax.swing.JButton();
        btnInsertTail = new javax.swing.JButton();
        btnQuit = new javax.swing.JButton();
        btnInsertBefore = new javax.swing.JButton();

        jButton1.setText("jButton1");

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblName.setText("Name");

        txtAreaList.setColumns(20);
        txtAreaList.setRows(5);
        scrollPaneList.setViewportView(txtAreaList);

        btnInsertHead.setText("Insert Head");
        btnInsertHead.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertHeadActionPerformed(evt);
            }
        });

        btnInsertTail.setText("Insert Tail");
        btnInsertTail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertTailActionPerformed(evt);
            }
        });

        btnQuit.setText("Quit");
        btnQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitActionPerformed(evt);
            }
        });

        btnInsertBefore.setText("Insert Before");
        btnInsertBefore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertBeforeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtName))
                    .addComponent(scrollPaneList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnQuit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnInsertTail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnInsertBefore, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnInsertHead, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPaneList, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnInsertHead)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnInsertBefore)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnInsertTail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnQuit)))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Insert Head
    private void btnInsertHeadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertHeadActionPerformed
        
        // get the name and create a new node
        String name = txtName.getText();
        DoubleNode node = new DoubleNode(name);
        
        names.insertHead(node);
        txtAreaList.setText(names.toString());
}//GEN-LAST:event_btnInsertHeadActionPerformed

    // Insert Tail
    private void btnInsertTailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertTailActionPerformed

        // Get the name and create a new node
        String name = txtName.getText();
        DoubleNode node = new DoubleNode(name);

        names.insertTail(node);
        txtAreaList.setText(names.toString());
    }//GEN-LAST:event_btnInsertTailActionPerformed

    // Quit
    private void btnQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnQuitActionPerformed

    // Insert Before
    private void btnInsertBeforeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertBeforeActionPerformed
        // Get the name and create a new node
        String name = txtName.getText();
        DoubleNode node = new DoubleNode(name);

        names.insertBefore(node);
        txtAreaList.setText(names.toString());
    }//GEN-LAST:event_btnInsertBeforeActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DoubleListAppGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInsertBefore;
    private javax.swing.JButton btnInsertHead;
    private javax.swing.JButton btnInsertTail;
    private javax.swing.JButton btnQuit;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel lblName;
    private javax.swing.JScrollPane scrollPaneList;
    private javax.swing.JTextArea txtAreaList;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables

}
