package page294_QueueDynamic;

import javax.swing.JOptionPane;

/**
 * A Swing application for managing a customer service queue.
 * @author Mark Hayes
 */
public class CustomerQueueAppGUI extends javax.swing.JFrame {

    /** Creates new form CustomerQueueApp */
    public CustomerQueueAppGUI() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblWelcome = new javax.swing.JLabel();
        panTakeNumber = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        lblPhone = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        txtName = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        panNextInQueue = new javax.swing.JPanel();
        lblNextInQueue = new javax.swing.JLabel();
        lblQueuelength = new javax.swing.JLabel();
        txtNextInQueue = new javax.swing.JTextField();
        txtQueuLength = new javax.swing.JTextField();
        btnRemove = new javax.swing.JButton();
        panSystemMessages = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        fileMenuExit = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        helpMenuInstallation = new javax.swing.JMenuItem();
        helpMenuOperation = new javax.swing.JMenuItem();
        helpMenuTroubleShoot = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("CIS Customer Service");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        lblWelcome.setFont(new java.awt.Font("Tahoma", 0, 14));
        lblWelcome.setForeground(new java.awt.Color(0, 0, 204));
        lblWelcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWelcome.setText("Welcome to CIS Customer Service");

        panTakeNumber.setBorder(javax.swing.BorderFactory.createTitledBorder(" Take a Number "));

        lblName.setText("Name");

        lblPhone.setText("Phone");

        btnAdd.setText("Add to Queue");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panTakeNumberLayout = new javax.swing.GroupLayout(panTakeNumber);
        panTakeNumber.setLayout(panTakeNumberLayout);
        panTakeNumberLayout.setHorizontalGroup(
            panTakeNumberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panTakeNumberLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panTakeNumberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panTakeNumberLayout.createSequentialGroup()
                        .addGroup(panTakeNumberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPhone, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panTakeNumberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPhone, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                            .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panTakeNumberLayout.createSequentialGroup()
                        .addComponent(btnAdd)
                        .addGap(30, 30, 30))))
        );
        panTakeNumberLayout.setVerticalGroup(
            panTakeNumberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panTakeNumberLayout.createSequentialGroup()
                .addGroup(panTakeNumberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panTakeNumberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPhone)
                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(btnAdd)
                .addContainerGap())
        );

        panNextInQueue.setBorder(javax.swing.BorderFactory.createTitledBorder(" Next in Queue "));

        lblNextInQueue.setText("Next in queue");

        lblQueuelength.setText("Queue length");

        txtNextInQueue.setBackground(new java.awt.Color(204, 204, 204));
        txtNextInQueue.setEditable(false);

        txtQueuLength.setBackground(new java.awt.Color(204, 204, 204));
        txtQueuLength.setEditable(false);

        btnRemove.setText("Remove");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panNextInQueueLayout = new javax.swing.GroupLayout(panNextInQueue);
        panNextInQueue.setLayout(panNextInQueueLayout);
        panNextInQueueLayout.setHorizontalGroup(
            panNextInQueueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panNextInQueueLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panNextInQueueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panNextInQueueLayout.createSequentialGroup()
                        .addGroup(panNextInQueueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblQueuelength, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblNextInQueue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panNextInQueueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNextInQueue, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                            .addComponent(txtQueuLength, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panNextInQueueLayout.createSequentialGroup()
                        .addComponent(btnRemove)
                        .addGap(37, 37, 37))))
        );
        panNextInQueueLayout.setVerticalGroup(
            panNextInQueueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panNextInQueueLayout.createSequentialGroup()
                .addGroup(panNextInQueueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNextInQueue)
                    .addComponent(txtNextInQueue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panNextInQueueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQueuelength)
                    .addComponent(txtQueuLength, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(btnRemove)
                .addContainerGap())
        );

        panSystemMessages.setBorder(javax.swing.BorderFactory.createTitledBorder(" System Messages "));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout panSystemMessagesLayout = new javax.swing.GroupLayout(panSystemMessages);
        panSystemMessages.setLayout(panSystemMessagesLayout);
        panSystemMessagesLayout.setHorizontalGroup(
            panSystemMessagesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panSystemMessagesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                .addContainerGap())
        );
        panSystemMessagesLayout.setVerticalGroup(
            panSystemMessagesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panSystemMessagesLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                .addContainerGap())
        );

        fileMenu.setText("File");

        fileMenuExit.setText("Exit");
        fileMenuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileMenuExitActionPerformed(evt);
            }
        });
        fileMenu.add(fileMenuExit);

        menuBar.add(fileMenu);

        helpMenu.setText("Help");

        helpMenuInstallation.setText("Installation");
        helpMenu.add(helpMenuInstallation);

        helpMenuOperation.setText("Operation");
        helpMenu.add(helpMenuOperation);

        helpMenuTroubleShoot.setText("Troubleshooting");
        helpMenu.add(helpMenuTroubleShoot);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblWelcome, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panTakeNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panNextInQueue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panSystemMessages, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblWelcome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panTakeNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panNextInQueue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panSystemMessages, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // User clicked on the Add button.
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddActionPerformed

    // User clicked on the Remove button.
    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRemoveActionPerformed

    // User clicked on File > Exit
    private void fileMenuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileMenuExitActionPerformed

        shutdownApplication();
    }//GEN-LAST:event_fileMenuExitActionPerformed

    /* User clicked on the X close-window button
     * This method is the actionListener for the "windowClosing" event for the
     * JFrame.
     * To Create the ActionListener for the JFrame:
     *   Design view > Inspector panel
     *   Right-click on the JFrame, select Properties
     *   1. Set "defaultCloseOperation" to DO_NOTHING
     *   2. Click on Events. Scroll down to the "windowClosing" event.
     *      Click on the down-arrow button to the right of <none>.
     *      Press the Close button.
     *      The actionListener method will be inserted into your code.
     */
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
                
        shutdownApplication();
    }//GEN-LAST:event_formWindowClosing

    /* Called when user selects File > Exit, or when user presses the
     * window-close button.
     */
    private void shutdownApplication()
    {
        int choice = JOptionPane.showConfirmDialog(this,
                "Are you sure you want to exit?", "Confirm Exit",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        if (choice == JOptionPane.YES_OPTION)
        {
            System.exit(0);
        }
    }

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerQueueAppGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnRemove;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuItem fileMenuExit;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuItem helpMenuInstallation;
    private javax.swing.JMenuItem helpMenuOperation;
    private javax.swing.JMenuItem helpMenuTroubleShoot;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNextInQueue;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblQueuelength;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JPanel panNextInQueue;
    private javax.swing.JPanel panSystemMessages;
    private javax.swing.JPanel panTakeNumber;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNextInQueue;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtQueuLength;
    // End of variables declaration//GEN-END:variables

}
